version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: carcar-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
    environment:
      FLASK_ENV: development
      FLASK_APP: src.app:app
    command: flask run --host=0.0.0.0
    networks:
      - carcar-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: carcar-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    networks:
      - carcar-network

networks:
  carcar-network:
    driver: bridge
